name: Deploy GitOps manifests

on:
  push:
    paths:
      - 'k8s/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: prd-devops-gha-runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Query ACM certificate ARN
        id: query_acm
        run: |
          ACM_ARN=$(aws acm list-certificates \
          --query "CertificateSummaryList[?DomainName=='*.indevops.io'].CertificateArn" \
          --output text)
          if [ -z "$ACM_ARN" ]; then
          echo "Error: ACM certificate ARN not found for domain 'indevops.io'"
          exit 1
          fi
          echo "ACM_ARN=$ACM_ARN" >> $GITHUB_ENV

      - name: Set SSL certificate for ingress
        working-directory: k8s/
        run: |
          sed -i "s|<ACM_CERT_ARN>|$ACM_ARN|g" 6-ingress.yaml

      - name: Authenticate to EKS
        run: |
          aws eks update-kubeconfig --name prd-devops-eks --region us-east-1
      
      - name: Deploy K8S manifests
        working-directory: k8s/
        run: |
          kubectl apply -f .

      - name: Verify application endpoints
        run: |
          for endpoint in "/welcome" "/kube-system-pods"; do
            url="https://demo.indevops.io${endpoint}"
            status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
            if [ "$status" -ne 200 ]; then
              echo "Error: Endpoint $url returned status code $status"
              exit 1
            fi
          done
          echo "All endpoints responded with status 200"
